### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by benglewis** [skeletonlabs/skeleton-datatables-integration#4]
Please add a license, ideally MIT to this repository 🙏

**Comment by endigo9740** [comment]
@benglewis Hey Ben, this should be covered under the same MIT License we display for the proper Skeleton project:

- https://github.com/skeletonlabs/skeleton?tab=MIT-1-ov-file#readme
- https://github.com/skeletonlabs/skeleton/blob/dev/LICENSE

I'm tied up between Skeleton and the recently announce Floating UI Svelte project, so I'd welcome a PR to add this. Should just be a matter of copying/pasting what's linked above. Just update the year to 2024-present please.

**Comment by benglewis** [comment]
@endigo9740 I added a PR, please merge it :) I cannot use this code without a license and I would very much like to work with this code
