### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'ctx[0].total') If result is = 0

### ISSUE THREAD

**Issue by TheBigMemph** [skeletonlabs/skeleton-datatables-integration#6]
When using server based datatables i need to calculate the totalRows depending on the database result. But when this database result.length = 0 i get the error:
`
TypeError: undefined is not an object (evaluating 'ctx[0].total')
`

I set the total rows after each database result:
```
handler.onChange(async (state: State) => {
const result = await trpc($page).exchangerates.test.query({ state, table });
state.setTotalRows(result.count);
return result.data;
});
```

When the database is returning count > 0 everything is working just fine.

It should say "No entries found":
```
#RowCount.svelte
	{#if $rowCount.total > 0}
		<b>{$rowCount.start}</b>
		- <b>{$rowCount.end}</b>
		/ <b>{$rowCount.total}</b>
	{:else}
		No entries found
	{/if}
```

**Comment by endigo9740** [comment]
Hey @TheBigMemph so two things here:

1. The datatables guides are provided "as is" from a community contributor. We merely host the guide as a boon to the community.
2. Anything released to Svelte Simple Datatables your database would be out of scope for support from myself and the Skeleton team.

To ensure you get the help you need, I might encourage you to reach out on either the [Svelte Simple Datatables community](https://github.com/vincjo/datatables/discussions)  and/or make a post in the [Skeleton Discord](https://discord.gg/EXqV7W8MtY) under one of the Community channels, such as `#off-topic`. We have many folks in the community that may be able to jump in and help.
